import correctionsData from "@/content/corrections.json";
import demandsData from "@/content/demands.json";
import governmentResponsesData from "@/content/government-responses.json";
import readingRoomData from "@/content/reading-room.json";
import timelineData from "@/content/timeline.json";
import updatesData from "@/content/updates.json";
import type {
  Correction,
  Demand,
  GovernmentResponse,
  ReadingItem,
  Resource,
  TimelineItem,
  Update,
} from "@/app/lib/content";

export const seededResources: Resource[] = [
  {
    id: "cjp-delhi-protest-hub",
    language: "en",
    title: "CJP Delhi Protest Hub",
    owner: "Cockroach Janta Party (CJP)",
    category: "Partner movement hub",
    summary: "CJP’s first-party Delhi protest page with organiser updates, campaign demands, press links, and participation material. Treat organiser claims as primary-source statements until independently verified.",
    href: "https://cockroachjantaparty.raizian.in/delhi-protest",
    reliability: "partner",
    reviewedAt: "2026-07-23",
  },
  {
    id: "cjp-delhi-protest-hub",
    language: "hi",
    title: "CJP दिल्ली प्रदर्शन हब",
    owner: "कॉकरोच जनता पार्टी (CJP)",
    category: "साझेदार आंदोलन हब",
    summary: "आयोजक अपडेट, अभियान की माँगें, प्रेस लिंक और भागीदारी सामग्री वाला CJP का प्रथम-पक्ष दिल्ली प्रदर्शन पेज। आयोजक के दावों को स्वतंत्र पुष्टि तक प्राथमिक-स्रोत बयान मानें।",
    href: "https://cockroachjantaparty.raizian.in/delhi-protest",
    reliability: "partner",
    reviewedAt: "2026-07-23",
  },
  {
    id: "india-tech-collective",
    language: "en",
    title: "India Tech Collective",
    owner: "The India Tech Collective",
    category: "Partner civic-tech toolkit",
    summary: "A non-partisan volunteer project curating open-source tools for digital rights, civic participation, accountability, and safer communication. Treat its tool descriptions as partner guidance and verify each tool's current security documentation independently.",
    href: "https://www.indiatechcollective.org/",
    reliability: "partner",
    reviewedAt: "2026-07-23",
  },
  {
    id: "india-tech-collective",
    language: "hi",
    title: "इंडिया टेक कलेक्टिव",
    owner: "द इंडिया टेक कलेक्टिव",
    category: "साझेदार नागरिक-तकनीक टूलकिट",
    summary: "डिजिटल अधिकार, नागरिक भागीदारी, जवाबदेही और सुरक्षित संचार के लिए मुक्त-स्रोत उपकरणों को संकलित करने वाली एक गैर-दलीय स्वयंसेवी परियोजना। इसके विवरणों को साझेदार मार्गदर्शन मानें और हर उपकरण के वर्तमान सुरक्षा दस्तावेज़ स्वतंत्र रूप से जाँचें।",
    href: "https://www.indiatechcollective.org/",
    reliability: "partner",
    reviewedAt: "2026-07-23",
  },
  {
    id: "nalsa-legal-aid",
    language: "en",
    title: "NALSA legal aid",
    owner: "National Legal Services Authority",
    category: "Legal aid",
    summary: "Official information about free legal services and access to legal-aid institutions in India.",
    href: "https://nalsa.gov.in/",
    reliability: "official",
    reviewedAt: "2026-07-23",
  },
  {
    id: "nalsa-legal-aid",
    language: "hi",
    title: "नालसा कानूनी सहायता",
    owner: "राष्ट्रीय विधिक सेवा प्राधिकरण",
    category: "कानूनी सहायता",
    summary: "भारत में निःशुल्क कानूनी सेवाओं और विधिक सहायता संस्थानों तक पहुँच की आधिकारिक जानकारी।",
    href: "https://nalsa.gov.in/",
    reliability: "official",
    reviewedAt: "2026-07-23",
  },
  {
    id: "sflc-digital-rights",
    language: "en",
    title: "SFLC.in",
    owner: "Software Freedom Law Center, India",
    category: "Digital rights",
    summary: "Indian digital-rights information, internet-shutdown tracking, and support resources.",
    href: "https://sflc.in/",
    reliability: "established",
    reviewedAt: "2026-07-23",
  },
  {
    id: "sflc-digital-rights",
    language: "hi",
    title: "एसएफएलसी.इन",
    owner: "सॉफ्टवेयर फ्रीडम लॉ सेंटर, इंडिया",
    category: "डिजिटल अधिकार",
    summary: "डिजिटल अधिकार, इंटरनेट बंदी की निगरानी और सहायता संसाधन।",
    href: "https://sflc.in/",
    reliability: "established",
    reviewedAt: "2026-07-23",
  },
  {
    id: "access-now-helpline",
    language: "en",
    title: "Digital Security Helpline",
    owner: "Access Now",
    category: "Digital security",
    summary: "Round-the-clock digital security support for civil-society groups, activists, journalists, and human-rights defenders.",
    href: "https://www.accessnow.org/help/",
    reliability: "established",
    reviewedAt: "2026-07-23",
  },
  {
    id: "access-now-helpline",
    language: "hi",
    title: "डिजिटल सुरक्षा हेल्पलाइन",
    owner: "एक्सेस नाउ",
    category: "डिजिटल सुरक्षा",
    summary: "नागरिक समाज, कार्यकर्ताओं, पत्रकारों और मानवाधिकार रक्षकों के लिए डिजिटल सुरक्षा सहायता।",
    href: "https://www.accessnow.org/help/",
    reliability: "established",
    reviewedAt: "2026-07-23",
  },
  {
    id: "eff-protest-safety",
    language: "en",
    title: "Attending a Protest",
    owner: "Electronic Frontier Foundation",
    category: "Protest safety",
    summary: "Practical digital-security considerations before, during, and after attending a protest.",
    href: "https://ssd.eff.org/ps/module/attending-protest",
    reliability: "established",
    reviewedAt: "2026-07-23",
  },
  {
    id: "eff-protest-safety",
    language: "hi",
    title: "प्रदर्शन में भाग लेते समय",
    owner: "इलेक्ट्रॉनिक फ्रंटियर फाउंडेशन",
    category: "प्रदर्शन सुरक्षा",
    summary: "प्रदर्शन में जाने से पहले, दौरान और बाद के लिए व्यावहारिक डिजिटल-सुरक्षा जानकारी।",
    href: "https://ssd.eff.org/ps/module/attending-protest",
    reliability: "established",
    reviewedAt: "2026-07-23",
  },
  {
    id: "shutdown-kit",
    language: "en",
    title: "Shutdown Kit",
    owner: "Community-built project",
    category: "Community toolkit",
    summary: "An external community toolkit for preparing for connectivity disruptions. Review it before use; it is not an official or independently verified TIP service.",
    href: "https://protest.uskhokhar.xyz/shutdown-kit",
    reliability: "community",
    reviewedAt: "2026-07-23",
  },
  {
    id: "shutdown-kit",
    language: "hi",
    title: "शटडाउन किट",
    owner: "समुदाय-निर्मित परियोजना",
    category: "सामुदायिक टूलकिट",
    summary: "कनेक्टिविटी बाधित होने की तैयारी के लिए बाहरी सामुदायिक टूलकिट। उपयोग से पहले समीक्षा करें; यह TIP की आधिकारिक या स्वतंत्र रूप से सत्यापित सेवा नहीं है।",
    href: "https://protest.uskhokhar.xyz/shutdown-kit",
    reliability: "community",
    reviewedAt: "2026-07-23",
  },
];

export const seededLandingSections = [
  {
    id: "what-is-happening",
    language: "en" as const,
    title: "What is going on?",
    body: "Students and young people are asking for fair examinations, action on paper leaks, and clear public accountability. The situation can change quickly, so this site separates confirmed facts from reports that still need checking.",
  },
  {
    id: "what-is-happening",
    language: "hi" as const,
    title: "क्या हो रहा है?",
    body: "छात्र और युवा निष्पक्ष परीक्षाओं, प्रश्नपत्र लीक पर कार्रवाई और स्पष्ट सार्वजनिक जवाबदेही की मांग कर रहे हैं। स्थिति जल्दी बदल सकती है, इसलिए यह साइट पुष्ट तथ्यों को उन रिपोर्टों से अलग रखती है जिनकी अभी जाँच बाकी है।",
  },
  {
    id: "why-tip",
    language: "en" as const,
    title: "Why The India Project exists",
    body: "We make participation safer, information clearer, and verified evidence harder to erase. We publish sources, timestamps, broad locations, uncertainty labels, and visible corrections.",
  },
  {
    id: "why-tip",
    language: "hi" as const,
    title: "द इंडिया प्रोजेक्ट क्यों है",
    body: "हम भागीदारी को सुरक्षित, जानकारी को स्पष्ट और सत्यापित प्रमाण को मिटाना कठिन बनाते हैं। हम स्रोत, समय, केवल व्यापक स्थान, अनिश्चितता के लेबल और स्पष्ट सुधार प्रकाशित करते हैं।",
  },
  {
    id: "what-we-are-not",
    language: "en" as const,
    title: "What this site is not",
    body: "This is not live location tracking, a rumour feed, a partisan campaign, or legal or medical advice. New source leads remain marked for review until an editor verifies them.",
  },
  {
    id: "what-we-are-not",
    language: "hi" as const,
    title: "यह साइट क्या नहीं है",
    body: "यह लाइव लोकेशन ट्रैकिंग, अफवाह फ़ीड, पक्षपातपूर्ण अभियान या कानूनी अथवा चिकित्सा सलाह नहीं है। नए स्रोत तब तक समीक्षा के लिए चिह्नित रहते हैं जब तक संपादक उन्हें सत्यापित न करे।",
  },
];

export const seededCollections = {
  updates: updatesData as Update[],
  demands: demandsData as Demand[],
  "government-responses": governmentResponsesData as GovernmentResponse[],
  timeline: timelineData as TimelineItem[],
  corrections: correctionsData as Correction[],
  "reading-room": readingRoomData as ReadingItem[],
  resources: seededResources,
  landing: seededLandingSections,
};
